name: E-Commerce Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest -n auto --alluredir=reports/allure-results
    
    - name: Generate Allure report
      if: always()
      uses: simple-elf/allure-report-action@v1
      with:
        allure_results: reports/allure-results
    
    - name: Upload Allure report as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: reports/allure-results
